// ========== NO FIREBASE ==========
// All data is loaded from mods.json (auto-generated by GitHub Actions)

// ========== WORKER URL (if needed for future bypass) ==========
// const WORKER_URL = 'https://modsfile-bypass.slherotech3.workers.dev';

// ========== HELPER ==========
function escapeHtml(str) {
    if (!str) return '';
    return str.replace(/[&<>]/g, function(m) {
        if (m === '&') return '&amp;';
        if (m === '<') return '&lt;';
        if (m === '>') return '&gt;';
        return m;
    });
}

// ========== DOWNLOAD MOD (modal with iframe) ==========
function downloadMod(modsfileUrl, buttonElement) {
    if (!modsfileUrl) {
        alert('No download link available.');
        return;
    }
    const modal = document.getElementById('downloadModal');
    const iframe = document.getElementById('modalIframe');
    iframe.src = modsfileUrl;
    modal.style.display = 'block';
}

function closeModal() {
    const modal = document.getElementById('downloadModal');
    const iframe = document.getElementById('modalIframe');
    iframe.src = 'about:blank';
    modal.style.display = 'none';
}

// ========== LOAD MODS FROM JSON FILE ==========
async function loadMods(search = "") {
    const container = document.getElementById("modsContainer");
    if (!container) return;
    container.innerHTML = "<div style='text-align:center; padding:2rem;'>Loading mods...</div>";

    try {
        const response = await fetch('mods.json');
        if (!response.ok) throw new Error('Failed to load mods.json');
        let mods = await response.json();

        if (search) {
            mods = mods.filter(mod => 
                mod.name.toLowerCase().includes(search) || 
                (mod.category && mod.category.toLowerCase().includes(search))
            );
        }

        if (mods.length === 0) {
            container.innerHTML = "<div style='text-align:center; padding:2rem;'>✨ No mods yet. Check back later!</div>";
            return;
        }

        container.innerHTML = "";
        mods.forEach(mod => {
            const downloadLink = mod.modsfileUrl || mod.downloadUrl;
            const category = mod.category || 'ETS2 Mod';
            const gameVersion = mod.gameVersion || '1.59';
            const author = mod.author || 'ETS2World';

            container.innerHTML += `
                <div class="mod-card">
                    <img src="${mod.imageUrl || 'https://via.placeholder.com/280x150?text=No+Image'}"
                         onerror="this.src='https://via.placeholder.com/280x150?text=No+Image'"
                         style="width:100%; height:150px; object-fit:cover; border-radius:10px;">
                    <h3>${escapeHtml(mod.name)}</h3>
                    <div class="mod-meta">📁 ${escapeHtml(category)} | 🎮 v${escapeHtml(gameVersion)}<br>✍️ ${escapeHtml(author)}</div>
                    <div class="mod-desc">${escapeHtml(mod.description || '')}</div>
                    <button class="download-btn" onclick="downloadMod('${escapeHtml(downloadLink)}', this)">⬇️ Download</button>
                </div>
            `;
        });
    } catch (err) {
        console.error("Error loading mods:", err);
        container.innerHTML = "<div style='text-align:center; padding:2rem;'>Error loading mods. Please try again later.</div>";
    }
}

// ========== SEARCH & INIT ==========
document.addEventListener("DOMContentLoaded", () => {
    const searchInput = document.getElementById("searchInput");
    if (searchInput) {
        searchInput.addEventListener("keyup", (e) => loadMods(e.target.value.toLowerCase()));
    }

    // Close modal when clicking outside
    window.onclick = function(event) {
        const modal = document.getElementById('downloadModal');
        if (event.target === modal) {
            closeModal();
        }
    };

    loadMods();
});